### ISSUE TITLE
Beacon Proximity is Inconsistent

### ISSUE THREAD

**Issue by mrchristopher124** [kontaktio/kontakt-ios-sdk#38]
Hello,

We are having some strange issues now that we've upgraded to the latest SDK. It took a while to get used to the new structure of things and also the delegate callbacks (would have been great to have a better migration guide here). It looks like we are now getting all of the proper delegate callbacks after quite a struggle, but unfortunately we are seeing some strange behavior with the method: func beaconManager(_ manager: KTKBeaconManager, didRangeBeacons beacons: [CLBeacon], in region: KTKBeaconRegion) {

Essentially, I am here with an iPad running an app that is integrated with the latest Kontakt.io SDK and I have one of our beacons right next to me. The didRangeBeacons delegate method gets called over and over again as we would expect, but the proximity for the beacon keeps changing state between Unknown, Near, Immediate when it should always be Near/Immediate since I'm literally  right next to the beacon. Very confused as to why it keeps giving back Unknown for stretches at a time and would rather not have to put in custom code to deal with this behavior. Note that I just updated via CocoaPods to the latest SDK version 1.3.3 and the beacon has the latest firmware 3.1. Also when I use the Kontakt.io iOS app it shows as the beacon being nearby and properly powered.

Here is some log output:

1885-35219 proximity: IMMEDIATE, 1
1885-35219 proximity: IMMEDIATE, 1
1885-35219 proximity: IMMEDIATE, 1
1885-35219 proximity: UNKNOWN, 0
1885-35219 proximity: UNKNOWN, 0
1885-35219 proximity: UNKNOWN, 0
1885-35219 proximity: UNKNOWN, 0
1885-35219 proximity: IMMEDIATE, 1
1885-35219 proximity: IMMEDIATE, 1
1885-35219 proximity: UNKNOWN, 0

Any info would be great. Not sure how to resolve this issue.

**Comment by stoprocent** [comment]
Hi @mrchristopher124 
Which SDK have you migrated from ? If you talking about this one https://github.com/kontaktio/SDK-iOS, it has been deprecated since more than a year ago :) 

In regards to your issue with `KTKBeaconManager` as long as you are not using secure/shuffled regions `KTKBeaconManager` is just a wrapper around `CLLocationManager`. `CLBeacon` is a `CoreLocation` object and proximity is calculated by the system (Apple). If you are getting strange results this is not really our SDK's fault :( I would try to maybe increase TX power?

Also just so you know latest Beacon firmware is **4.2** but to go from **3.1** to **4.2** you have to approve this update from our web panel.

**Comment by mrchristopher124** [comment]
@stoprocent ok cool! I will do that approval and try the latest firmware. Yeah the app was on an old old SDK. Hopefully the firmware update will help and I'll try boosting the TX powah. Thanks man! Will try this stuff out tonight.

**Comment by mrchristopher124** [comment]
OK did another firmware update and made a slight code adjustment. Good to go. Thanks for the help!
