### ISSUE TITLE
KTKDeviceManger want to search only beacons Which are registered in my console

### ISSUE THREAD

**Issue by miraldhokiya** [kontaktio/kontakt-ios-sdk#39]
Hello , 

I am Using Kontakt.io latest sdk in Objective C.

In my mobile application i want to search ,only beacons which are registered in my console account.
Currently i have implemented my code as below.

// Setting API Key to Kontakt 
[Kontakt setAPIKey:@"HNsIEXoeYNgnBnJFnADWytZrlSkjaZko"];

// Initializing KTKDeviceManager Obj
devicesManager = [[KTKDevicesManager alloc] initWithDelegate:self];
  
// Start discovering beacons    
[devicesManager startDevicesDiscovery];

//Delegate method in my class
-(void)devicesManager:(KTKDevicesManager *)manager didDiscoverDevices:(NSArray<KTKNearbyDevice *> *)devices{
    if(devices.count >0){
      for(int i=0;i<devices.count;i++){
         KTKNearbyDevice *device = [devices objectAtIndex:i];
         NSLog(@"devicesManager Method Call - UniqueID -%@",device.uniqueID);
         }   
}

Here i am getting beacons which are registered in my console , and other beacon which is near by.

Please guide me how to get only beacons which are registered in my console.

**Comment by adrianz** [comment]
Hi @miraldhokiya 

I'm terribly sorry for not responding earlier. Our SDK does not have a method just for filtering out not your beacons. However, I don't think it should be to hard to implement on your own. For example, you can take advantage of the API Client from our SDK and get a list of all your beacons that you can use to filter `KTKNearbyDevice` array from `didDiscoverDevices` method.

Since this is not really an issue with our SDK, I'm going to close this, but if you need help with implementing our SDK in your app I might suggest subscribing to our [Premium Support plans](https://support.kontakt.io/hc/en-gb/articles/206928570).
